TMUX_CONFIG_DIR=$HOME/.config/tmux

setenv -g  TMUX_CONFIG_DIR          "$TMUX_CONFIG_DIR"
setenv -g  TMUX_PLUGIN_MANAGER_PATH "$TMUX_CONFIG_DIR/plugins"
setenv -g  TMUX_THEME               "$TMUX_CONFIG_DIR/meta.min.tmuxtheme"

source $TMUX_CONFIG_DIR/colors.tmux
source $TMUX_CONFIG_DIR/profile.tmux
source $TMUX_CONFIG_DIR/keybindings.tmux

set-hook -g  window-linked   'source ${TMUX_THEME}'
set-hook -g  session-created 'source ${TMUX_THEME}'
set-hook -g  session-renamed 'source ${TMUX_THEME}'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'aserowy/tmux.nvim'

set -g @tmux-nvim-navigation true
set -g @tmux-nvim-navigation-cycle true

set -g @tmux-nvim-resize true
set -g @tmux-nvim-resize-step-x 1
set -g @tmux-nvim-resize-step-y 1
set -g @tmux-nvim-resize-keybinding-left 'C-M-h'
set -g @tmux-nvim-resize-keybinding-down 'C-M-j'
set -g @tmux-nvim-resize-keybinding-up 'C-M-k'
set -g @tmux-nvim-resize-keybinding-right 'C-M-l'

set -g @tmux-nvim-swap false



# set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'christoomey/vim-tmux-navigator'

# run '~/.tmux/plugins/tpm/tpm'

run "$TMUX_CONFIG_DIR/plugins/tpm/tpm"

# vim:ft=tmux
